# Generated by Django 5.2 on 2026-04-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIPlannedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Calculé par l'IA"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Basse"), (2, "Moyenne"), (3, "Haute")], default=2
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("is_completed", models.BooleanField(default=False)),
                ("ai_generated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
